@echo off
chcp 65001
cls
echo Введите путь до исполняемого файла программы BOCHS - Enter the path to the BOCHS program directory
set /p BOCHS_PATH=Path: 

set BIN_PATH=%~dp0\bin\BootLoader.bin

echo # configuration file generated by Bochs >bochsrc.bxrc
echo plugin_ctrl: voodoo=false, unmapped=true, biosdev=true, speaker=true, extfpuirq=true, parallel=true, serial=true, busmouse=false, e1000=false, es1370=false, gameport=true, ne2k=false, sb16=false, usb_uhci=false, usb_ohci=false, usb_ehci=false, usb_xhci=false >>bochsrc.bxrc
echo config_interface: win32config >>bochsrc.bxrc
echo display_library: win32 >>bochsrc.bxrc
echo memory: guest=32, host=32, block_size=128 >>bochsrc.bxrc
echo romimage: file="C:\Program Files\Bochs-2.8\BIOS-bochs-latest", address=0x00000000, options=none, flash_data=none >>bochsrc.bxrc
echo vgaromimage: file="%BOCHS_PATH%\VGABIOS-lgpl-latest" >>bochsrc.bxrc
echo boot: floppy >>bochsrc.bxrc
echo floppy_bootsig_check: disabled=0 >>bochsrc.bxrc
echo floppya: type=1_44, 1_44="%BIN_PATH%", status=inserted, write_protected=0 >>bochsrc.bxrc
echo # no floppyb >>bochsrc.bxrc
echo ata0: enabled=true, ioaddr1=0x1f0, ioaddr2=0x3f0, irq=14 >>bochsrc.bxrc
echo ata0-master: type=none >>bochsrc.bxrc
echo ata0-slave: type=none >>bochsrc.bxrc
echo ata1: enabled=true, ioaddr1=0x170, ioaddr2=0x370, irq=15 >>bochsrc.bxrc
echo ata1-master: type=none >>bochsrc.bxrc
echo ata1-slave: type=none >>bochsrc.bxrc
echo ata2: enabled=false >>bochsrc.bxrc
echo ata3: enabled=false >>bochsrc.bxrc
echo optromimage1: file=none >>bochsrc.bxrc
echo optromimage2: file=none >>bochsrc.bxrc
echo optromimage3: file=none >>bochsrc.bxrc
echo optromimage4: file=none >>bochsrc.bxrc
echo optramimage1: file=none >>bochsrc.bxrc
echo optramimage2: file=none >>bochsrc.bxrc
echo optramimage3: file=none >>bochsrc.bxrc
echo optramimage4: file=none >>bochsrc.bxrc
echo pci: enabled=1, chipset=i440fx, slot1=none, slot2=none, slot3=none, slot4=none, slot5=none >>bochsrc.bxrc
echo vga: extension=vbe, update_freq=10, realtime=1, ddc=builtin >>bochsrc.bxrc
echo cpu: count=1, ips=4000000, model=bx_generic, reset_on_triple_fault=1, cpuid_limit_winnt=0, ignore_bad_msrs=1, mwait_is_nop=0 >>bochsrc.bxrc
echo cpuid: level=6, stepping=3, model=3, family=6, vendor_string="GenuineIntel", brand_string="              Intel(R) Pentium(R) 4 CPU        " >>bochsrc.bxrc
echo cpuid: mmx=true, apic=xapic, simd=sse2, sse4a=false, misaligned_sse=false, sep=true >>bochsrc.bxrc
echo cpuid: movbe=false, adx=false, aes=false, sha=false, xsave=false, xsaveopt=false, avx_f16c=false >>bochsrc.bxrc
echo cpuid: avx_fma=false, bmi=0, xop=false, fma4=false, tbm=false, x86_64=true, 1g_pages=false >>bochsrc.bxrc
echo cpuid: pcid=false, fsgsbase=false, smep=false, smap=false, mwait=true, vmx=1, svm=false >>bochsrc.bxrc
echo print_timestamps: enabled=0 >>bochsrc.bxrc
echo port_e9_hack: enabled=false, all_rings=false >>bochsrc.bxrc
echo private_colormap: enabled=0 >>bochsrc.bxrc
echo clock: sync=none, time0=local, rtc_sync=0 >>bochsrc.bxrc
echo # no cmosimage >>bochsrc.bxrc
echo log: - >>bochsrc.bxrc
echo logprefix: %t%e%d >>bochsrc.bxrc
echo debug: action=ignore >>bochsrc.bxrc
echo info: action=report >>bochsrc.bxrc
echo error: action=report >>bochsrc.bxrc
echo panic: action=ask >>bochsrc.bxrc
echo keyboard: type=mf, serial_delay=150, paste_delay=100000, user_shortcut=none >>bochsrc.bxrc
echo mouse: type=ps2, enabled=false, toggle=ctrl+mbutton >>bochsrc.bxrc
echo sound: waveoutdrv=win, waveout=none, waveindrv=win, wavein=none, midioutdrv=win, midiout=none >>bochsrc.bxrc
echo speaker: enabled=true, mode=sound, volume=15 >>bochsrc.bxrc
echo parport1: enabled=true, file=none >>bochsrc.bxrc
echo parport2: enabled=false >>bochsrc.bxrc
echo com1: enabled=true, mode=null >>bochsrc.bxrc
echo com2: enabled=false >>bochsrc.bxrc
echo com3: enabled=false >>bochsrc.bxrc
echo com4: enabled=false >>bochsrc.bxrc